Gen queeres from contacts and audit wd lexemes

diff --git a/.github/workflows/audit_missing_query_forms.yaml b/.github/workflows/audit_missing_query_forms.yaml
--- a/.github/workflows/audit_missing_query_forms.yaml
+++ b/.github/workflows/audit_missing_query_forms.yaml
@@ -1,4 +1,4 @@
-name: check_and_update_missing_query_forms
+name: audit_missing_query_forms
 on:
   schedule:
     # Runs at 00:00 UTC on the first day of every month.
@@ -45,7 +45,7 @@ jobs:
       - name: Generate Missing Features Data
         run: |
           # Set up paths
-          QUERY_DIR="$(pwd)/src/scribe_data/wikidata/queries_all_data"
+          QUERY_DIR="$(pwd)/src/scribe_data/wikidata/queries"
 
           echo "Query directory: ${QUERY_DIR}"
 
@@ -64,7 +64,7 @@ jobs:
 
       - name: Make Changes
         run: |
-          git add src/scribe_data/wikidata/queries_all_data/**/*.sparql
+          git add src/scribe_data/wikidata/queries/**/*.sparql
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
 
@@ -87,14 +87,15 @@ jobs:
 
       - name: Post-run Status
         if: failure()
-        run: echo "Generated SPARQL query forms or identifiers check failed. Please fix
+        run:
+          echo "Generated SPARQL query forms or identifiers check failed. Please fix
           the reported errors."
 
       - name: Generate PR Body
         id: pr-body
         run: |
-          # Run the pr_body.py script with the missing features data.
-          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py query_check_missing_features.json) || echo "No missing query forms found."
+          # Run the issue_body.py script with the missing features data.
+          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/issue_body.py query_check_missing_features.json) || echo "No missing query forms found."
 
           # Debug output.
           # echo "PR Body Content:"
