Remove double negative and add identifiers check

diff --git a/.github/workflows/check_and_update_missing_query_forms.yaml b/.github/workflows/check_and_update_missing_query_forms.yaml
--- a/.github/workflows/check_and_update_missing_query_forms.yaml
+++ b/.github/workflows/check_and_update_missing_query_forms.yaml
@@ -80,23 +80,24 @@ jobs:
       - name: check generated query forms
         working-directory: ./src/scribe_data/check
         run: |
+          python check_query_identifiers.py
           python check_query_forms.py
 
       - name: Post-run status
         if: failure()
-        run: echo "Generated SPARQL query forms check failed. Please fix the reported errors."
+        run: echo "Generated SPARQL query forms or identifiers check failed. Please fix the reported errors."
 
       - name: Generate PR Body
         id: pr-body
         run: |
           # Run the pr_body.py script with the missing features data.
-          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py query_check_missing_features.json) || echo "No missing features/forms found."
+          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py query_check_missing_features.json) || echo "All query forms and identifiers are correct."
 
           # Debug output.
           # echo "PR Body Content:"
           # echo "$PR_BODY_CONTENT"
 
-          # Initialize PR body with delimiter
+          # Initialize PR body with delimiter.
           {
             echo "body<<EOF"
             echo "$PR_BODY_CONTENT"
@@ -110,7 +111,7 @@ jobs:
       #     cat $GITHUB_OUTPUT
 
       - name: Create Pull Request
-        if: steps.pr-body.outputs.body != 'No missing features/forms found.'
+        if: steps.pr-body.outputs.body == 'All query forms and identifiers are correct.'
         uses: peter-evans/create-pull-request@v5
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
